# Ethereum RPC URL (replace with your own)
rpc_url = "https://hyperion-testnet.metisdevops.link"

# Private key for the trading account (hex string without 0x prefix)
# IMPORTANT: This is just an example. Never commit your real private key to version control!
private_key = "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"

# Base URL for Kuma Push service
base_kuma_url = "http://kuma"

# Push ID used to track that bot is actually running
general_push_id = "pushID"

# The address of Uniswap V2 router
uniswap_v2_router = "0xa1cF48c109f8B5eEe38B406591FE27f11f685a1f"

# The address of Mortal coin game contract
game_contract = "0xDf8730693833b9e27D5999863feBb3028fcc6927"

# List of pairs to trade, need to have a direct UniswapV2Pair
# Contains Kuma push ID to monitor status of specific pair
[[pairs]]
name = "WETH-USDT"
token0 = "0x231dfCFd9dEF41f86f5b7AB77ef0946C0Cda3B1B"
min_balance0 = 10000
token1 = "0x3512B762158FF2caCb0551215618Ec2dF303FDD9"
min_balance1 = 1000000000000
pair_address = "0x9d5868afd7e4DdAEc6Cd6D45de7C268D912bf8a6"
kuma_push_id = "pushID"
kraken_pair = "ETHUSD"
reverse_kraken_pair = false
